language: php
php:
  - 7.4

addons:
    mariadb: 10.3

cache:
  directories:
    - vendor
    - $HOME/.composer/cache
    - $HOME/.cache/yarn
    - node_modules

before_install:
  - nvm install 12
  - nvm use 12
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yes | pecl install imagick

before_script:
  - mysql -e 'CREATE DATABASE artisans; SET GLOBAL sql_mode = "";'
  - cp config/autoload/local.php.dist config/autoload/local.php
  - ./bin/build.sh
  - ./bin/load-test-data.php

script:
  - ./vendor/bin/doctrine orm:validate-schema
  - ./vendor/bin/php-cs-fixer fix --diff --verbose --dry-run
  - ./vendor/bin/phpunit --coverage-clover coverage-clover.xml
  - ./vendor/bin/phpstan analyse
  - yarn lint
  - ./node_modules/.bin/ng test --progress false --watch=false --browsers ChromeHeadlessCustom

after_script:
  - wget https://scrutinizer-ci.com/ocular.phar && php ocular.phar code-coverage:upload --format=php-clover coverage-clover.xml
