<?php declare(strict_types=1);
$urlTransaction = $this->serverUrl . '/profile/history';
$urlServices = $this->serverUrl . '/profile/services';
?>
<p>
    Ton solde actuel est de
    <span style="text-align: right; font-weight: bold; color: <?php echo $this->user->getAccount()->getBalance() < 0 ? '#f44336' : '#008600' ?>">
        <?php echo $this->user->getAccount()->getBalance() ?> CHF</span>.
</p>

<?php if ($this->user->getAccount()->getBalance() < 0): ?>
    <p>Ton solde est insuffisant. Merci de <a href="<?php echo $urlTransaction ?>">faire un versement</a> et/ou ajuster <a
                href="<?php echo $urlServices ?>">les services utilisés</a>.</p>

    <p style="text-align:center;margin:40px 0">
        <a href="<?php echo $urlTransaction ?>"
           style="padding:10px; background:#3176a2; text-decoration:none; color:white;">
            Faire un versement
        </a>
    </p>
    <p>Si le solde devient trop négatif, tu ne pourras plus utiliser les services d'Ichtus.</p>

<?php else: ?>
    <p>Ton solde est suffisant et tu n'as donc rien besoin de faire.</p>
<?php endif; ?>


<p>Pour rappel, tes prestations annuelles sont:</p>

<table style="margin-left: 2em; min-width: 300px; border-collapse: collapse">
    <?php foreach ($this->bookables as $bookable): ?>
        <tr>
            <td><?php echo $bookable->getName() ?></td>
            <td style="text-align: right"><?php echo $bookable->getPeriodicPrice() ?> CHF</td>
        </tr>
    <?php endforeach; ?>
</table>

<p>Voir aussi <a href="<?php echo $urlTransaction ?>">l'historique du compte</a> et <a
            href="https://ichtus.ch/le-club/philosophie/">les FAQ de facturation</a>.</p>
