<?php declare(strict_types=1);

use Money\Currencies\ISOCurrencies;
use Money\Formatter\DecimalMoneyFormatter;

$currencies = new ISOCurrencies();
$moneyFormatter = new DecimalMoneyFormatter($currencies);

$urlTransaction = $this->serverUrl . '/profile/history';
?>
<p>
    Ton solde actuel est de
    <span style="text-align: right; font-weight: bold; color: <?php echo $this->user->getAccount()->getBalance()->isNegative() ? '#f44336' : '#008600' ?>">
        <?php echo $moneyFormatter->format($this->user->getAccount()->getBalance()) ?> CHF</span>.
</p>

<?php if ($this->user->getAccount()->getBalance()->isNegative()): ?>
    <p>Ton solde est insuffisant. Merci de <a href="<?php echo $urlTransaction ?>">faire un versement</a>.</p>

    <p style="text-align:center;margin:40px 0">
        <a href="<?php echo $urlTransaction ?>"
           style="padding:10px; background:#a4ce4c; text-decoration:none; color:white;">
            Faire un versement
        </a>
    </p>
    <p>Si le solde devient trop négatif, tu ne pourras plus utiliser les services d'Emmy.</p>

<?php else: ?>
    <p>Ton solde est suffisant et tu n'as donc rien besoin de faire.</p>
<?php endif; ?>


<p>Voir aussi <a href="<?php echo $urlTransaction ?>">l'historique du compte</a> et <a
            href="https://about.emmy.ch">les FAQ de facturation</a>.</p>
