<?php declare(strict_types=1);
$urlProfile = $this->serverUrl . '/profile';
$urlServices = $this->serverUrl . '/profile/services';
?>
<p>Les services suivants ont été débité de ton compte:</p>

<table style="min-width: 300px; border-collapse: collapse">
    <?php foreach ($this->transaction->getTransactionLines() as $line): ?>
        <tr>
            <td><?php echo $line->getBookable()->getName() ?></td>
            <td style="text-align: right"><?php echo $line->getBalance() ?> CHF</td>
        </tr>
    <?php endforeach; ?>
    <tr style="font-weight: bold">
        <td style="border-top: 1px #494949 solid">TOTAL</td>
        <td style="border-top: 1px #494949 solid; text-align: right"><?php echo $this->total ?> CHF</td>
    </tr>
    <tr>
        <td>&nbsp;</td>
        <td></td>
    </tr>
    <tr>
        <td>Solde avant</td>
        <td style="text-align: right"><?php echo bcadd($this->user->getAccount()->getBalance(), $this->total, 2) ?> CHF</td>
    </tr>
    <tr>
        <td>Solde après</td>
        <td style="text-align: right; font-weight: bold; color: <?php echo $this->user->getAccount()->getBalance() < 0 ? '#f44336' : '#008600' ?>">
            <?php echo $this->user->getAccount()->getBalance() ?> CHF
        </td>
    </tr>
</table>

<?php if ($this->user->getAccount()->getBalance() < 0): ?>
    <p>Ton solde est insuffisant. Merci de <a href="<?php echo $urlProfile ?>">faire un versement</a> et/ou ajuster <a
                href="<?php echo $urlServices ?>">les services utilisés</a>.</p>

    <p style="text-align:center;margin:40px 0">
        <a href="<?php echo $urlProfile ?>"
           style="padding:10px; background:#3176a2; text-decoration:none; color:white;">
            Faire un versement
        </a>
    </p>
    <p>Si le solde devient trop négatif, tu ne pourras plus utiliser les services d'Ichtus.</p>

<?php else: ?>
    <p>Ton solde est suffisant. Tu n'as rien besoin de faire.</p>
<?php endif; ?>

