<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <title><?php echo $this->escapeHtml($this->subject) ?></title>
        <style type="text/css">

            body, html, td {
                font-family: "Trebuchet MS", Helvetica, sans-serif;
                font-size: 14px;
                line-height: 1.8em;
                color: #494949;
                background: #fafafa;
            }

            body, html {
                padding: 0;
                margin: 0;
            }

            a {
                color: #EF6031;
            }
        </style>
    </head>

    <body>

        <div style="background:#f5f5f5; padding:20px">
            <div style="max-width:650px; width:100%; margin: auto;">
                <a href="<?php echo $this->serverUrl ?>" style="text-decoration:none; color:#494949; font-size:20px; font-weight:bold;">
                    <img src="<?php echo $this->serverUrl ?>/assets/logo-artisans-de-la-transition.svg"
                         border="0"
                         width="360"
                         height="40"
                         style="vertical-align:middle;margin-right:20px"
                         alt="Les artisans de la transition"
                    />
                </a>
            </div>
        </div>

        <div style="padding:30px 20px">
            <div style="max-width:650px; width:100%; margin: auto;">
                <p>Bonjour<?php echo $this->escapeHtml($this->user && $this->user->getName() ? ' ' . $this->user->getName() : '') ?>,</p>
                <?php echo $this->content; ?>
            </div>
        </div>

        <div style="padding:16px; background:#f5f5f5;">
            <div style="max-width:650px; width:100%; margin:auto; padding:0 20px">
                <p style="font-weight:bold; margin-bottom:0">
                    Les artisans de la transition, Rue de Lausanne 23, 1700 Fribourg
                </p>
                <p style="font-size: 0.8em; margin-top:0;">
                    Ceci est un message automatique de notification envoyé par
                    <a href="<?php echo $this->serverUrl ?>" style="text-decoration:none;"><?php echo $this->escapeHtml($this->hostname) ?></a>, n'y répondez pas.
                </p>
            </div>
        </div>

    </body>
</html>
