<html>
    <head>
        <meta http-equiv="content-type" content="text/html; charset=utf-8">
        <?php echo $this->headTitle(); ?>

        <style type="text/css" title="text/css">

            body, html, td {
                font-family: "Trebuchet MS", Helvetica, sans-serif;
                font-size: 14px;
                line-height: 1.8em;
                color: #494949;
            }
            body, html {
                padding: 0;
                margin: 0;
                background: #3176a2;
            }

            a {
                color: #3176a2;
            }
        </style>
    </head>

    <body>

        <div style="background:#f5f5f5; padding:20px">
            <div style="max-width:650px; width:100%; margin: auto;">
                <a href="<?php echo $this->serverUrl ?>" style="text-decoration:none; color:#494949; font-size:20px; font-weight:bold;">
                    <img src="<?php echo $this->serverUrl ?>/assets/emmy.png"
                         border="0"
                         width="60"
                         height="60"
                         style="vertical-align:middle"
                    /> coopérative Chez Emmy
                </a>
            </div>
        </div>

        <div style="background: #fafafa; padding:0 20px">
            <div style="max-width:650px; width:100%; margin: auto; padding:30px 0;">
                <p>Hello<?php echo $this->user && $this->user->getFirstName() ? ' ' . $this->escapeHtml($this->user->getFirstName()) : '' ?>,</p>
                <?php echo $this->content; ?>
            </div>
        </div>

        <div style="background:#3176a2; color: white; padding:16px;">
            <div style="max-width:650px; width:100%; margin:auto; padding:0 20px">
                <p style="font-weight:bold; margin-bottom:0">
                    coopérative Chez Emmy, 2072 St-Blaise - Réalisation Ecodev
                </p>
                <p style="font-size: 0.8em; margin-top:0;">
                    Ceci est un message automatique de notification envoyé par
                    <a href="<?php echo $this->serverUrl ?>" style="text-decoration:none; color:#cce4ee;"><?php echo $this->hostname ?></a>, n'y répond pas.
                </p>
            </div>
        </div>

    </body>
</html>
