<?php declare(strict_types=1);
$url = $this->serverUrl . '/user/change-password/' . $this->token;
?>
<p>
    Une demande de modification de mot de passe a été faite pour l'email "<?php echo $this->user->getEmail() ?>".
    Pour choisir un nouveau mot de passe, cliquez sur le bouton ci-dessous :
</p>

<p style="text-align:center;margin:40px 0">
    <a href="<?php echo $url ?>" style="padding:10px; background:#a4ce4c; text-decoration:none; color:white;">
        Définir un mot de passe
    </a>
</p>

<p>
    Si vous n'êtes pas à l'origine de cette demande, vous pouvez simplement ignorer cet email.
</p>

