<?php declare(strict_types=1);
$url = $this->serverUrl . '/user/change-password/' . $this->token;
?>
<p>L’utilisateur <?php echo $this->escapeHtml($this->user->getEmail()) ?> a demandé un nouveau mot de passe. Pour l’obtenir, cliquez sur le bouton ci-dessous :</p>

<p style="text-align:center;margin:40px 0">
    <a href="<?php echo $url ?>" style="padding:10px; text-decoration:none; color:white; background:#EF6031;">
        Définir un mot de passe
    </a>
</p>

<p>Si vous n’êtes pas à l’origine de cette demande, vous pouvez ignorer ce message.</p>

