<?php declare(strict_types=1);
$url = $this->serverUrl . '/admin/user/' . $this->unregisteredUser->getId();
?>
<p>La personne suivante ne souhaite plus faire partie de l’association :</p>

<ul>
    <li><?php echo $this->escapeHtml($this->unregisteredUser->getName()) ?></li>
    <?php if ($this->unregisteredUser->getEmail()) { ?>
        <li>
            <a href="mailto:<?php echo $this->escapeHtmlAttr($this->unregisteredUser->getEmail()) ?>"><?php echo $this->escapeHtml($this->unregisteredUser->getEmail()) ?></a>
        </li>
    <?php } ?>
    <li><a href="<?php echo $url ?>"><?php echo $this->escapeHtml($url) ?></a></li>
</ul>


