<?php declare(strict_types=1);
$url = $this->serverUrl . '/admin/user/' . $this->updatedUser->getId();
?>
<p>L'utilisateur suivant a modifié ses information personnelles :</p>

<table style="min-width: 20em;">
    <tr>
        <th></th>
        <th>Avant</th>
        <th>Après</th>
    </tr>
    <?php foreach ($this->before as $key => $value): ?>
        <tr>
            <td><?php echo $this->escapeHtml($key) ?></td>
            <td<?php echo $value !== $this->after[$key] ? ' style="color: red"' : '' ?>><?php echo $this->escapeHtml($value) ?></td>
            <td<?php echo $value !== $this->after[$key] ? ' style="color: green"' : '' ?>><?php echo $this->escapeHtml($this->after[$key]) ?></td>
        </tr>
    <?php endforeach; ?>
</table>

<p>Contacter l'utilisateur :</p>
<ul>
    <li><?php echo $this->updatedUser->getName() ?></li>
    <li>
        <a href="mailto:<?php echo $this->escapeHtmlAttr($this->updatedUser->getEmail()) ?>"><?php echo $this->escapeHtml($this->updatedUser->getEmail()) ?></a>
    </li>
    <li><a href="<?php echo $url ?>"><?php echo $this->escapeHtml($url) ?></a></li>
</ul>
