<?php declare(strict_types=1);
$url = $this->serverUrl . '/mon-compte/commandes/' . $this->order->getId();
?>
<p>Nous vous remercions de votre commande. Vous recevrez bientôt une facture avec les informations nécessaires pour le paiement.</p>
<p>Détails de la commande :</p>

<?php echo $this->orderLines($this->order); ?>

<p>Voir le détail sur <a href="<?php echo $url ?>"><?php echo $this->escapeHtml($url) ?></a>.</p>
