<?php declare(strict_types=1);
$this->headTitle(sprintf('%d %s', $this->status, $this->reason)); ?>

<h1>Oops!</h1>
<p>We encountered a <?php echo $this->escapeHtml(sprintf('%d %s', $this->status, $this->reason)) ?> error.</p>
<?php if ($this->status === 404) { ?>
    <p>
        You are looking for something that doesn't exist or may have moved. Head back to <a href="/">Home</a>.
    </p>
<?php } ?>
<pre><?php echo $this->escapeHtml($this->error) ?></pre>
