<?php

declare(strict_types=1);

namespace Application\Migration;

use Doctrine\DBAL\Schema\Schema;

class Version20190409081305 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('ALTER TABLE log DROP FOREIGN KEY FK_8F3F68C561220EA6');
        $this->addSql('ALTER TABLE log DROP FOREIGN KEY FK_8F3F68C57E3C61F9');
        $this->addSql('ALTER TABLE log DROP FOREIGN KEY FK_8F3F68C5E37ECFB0');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C561220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C57E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C5E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D64961220EA6');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D6497E3C61F9');
        $this->addSql('ALTER TABLE user DROP FOREIGN KEY FK_8D93D649E37ECFB0');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D64961220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D6497E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_tag DROP FOREIGN KEY FK_E89FD60861220EA6');
        $this->addSql('ALTER TABLE user_tag DROP FOREIGN KEY FK_E89FD6087E3C61F9');
        $this->addSql('ALTER TABLE user_tag DROP FOREIGN KEY FK_E89FD608E37ECFB0');
        $this->addSql('ALTER TABLE user_tag ADD CONSTRAINT FK_E89FD60861220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_tag ADD CONSTRAINT FK_E89FD6087E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_tag ADD CONSTRAINT FK_E89FD608E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F61220EA6');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307F7E3C61F9');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FE37ECFB0');
        $this->addSql('ALTER TABLE message DROP FOREIGN KEY FK_B6BD307FE92F8F78');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F61220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FE37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FE92F8F78 FOREIGN KEY (recipient_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bookable DROP FOREIGN KEY FK_A10B812461220EA6');
        $this->addSql('ALTER TABLE bookable DROP FOREIGN KEY FK_A10B81247E3C61F9');
        $this->addSql('ALTER TABLE bookable DROP FOREIGN KEY FK_A10B8124E37ECFB0');
        $this->addSql('ALTER TABLE bookable ADD CONSTRAINT FK_A10B812461220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookable ADD CONSTRAINT FK_A10B81247E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookable ADD CONSTRAINT FK_A10B8124E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE image DROP FOREIGN KEY FK_C53D045F61220EA6');
        $this->addSql('ALTER TABLE image DROP FOREIGN KEY FK_C53D045F7E3C61F9');
        $this->addSql('ALTER TABLE image DROP FOREIGN KEY FK_C53D045FE37ECFB0');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045F61220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045FE37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE country DROP FOREIGN KEY FK_5373C96661220EA6');
        $this->addSql('ALTER TABLE country DROP FOREIGN KEY FK_5373C9667E3C61F9');
        $this->addSql('ALTER TABLE country DROP FOREIGN KEY FK_5373C966E37ECFB0');
        $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C96661220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C9667E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE country ADD CONSTRAINT FK_5373C966E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE account DROP FOREIGN KEY FK_7D3656A461220EA6');
        $this->addSql('ALTER TABLE account DROP FOREIGN KEY FK_7D3656A47E3C61F9');
        $this->addSql('ALTER TABLE account DROP FOREIGN KEY FK_7D3656A4E37ECFB0');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A461220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A47E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A4E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction_tag DROP FOREIGN KEY FK_F8CD024A61220EA6');
        $this->addSql('ALTER TABLE transaction_tag DROP FOREIGN KEY FK_F8CD024A7E3C61F9');
        $this->addSql('ALTER TABLE transaction_tag DROP FOREIGN KEY FK_F8CD024AE37ECFB0');
        $this->addSql('ALTER TABLE transaction_tag ADD CONSTRAINT FK_F8CD024A61220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction_tag ADD CONSTRAINT FK_F8CD024A7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction_tag ADD CONSTRAINT FK_F8CD024AE37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDE61220EA6');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDE7E3C61F9');
        $this->addSql('ALTER TABLE booking DROP FOREIGN KEY FK_E00CEDDEE37ECFB0');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE61220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDE7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE booking ADD CONSTRAINT FK_E00CEDDEE37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookable_metadata DROP FOREIGN KEY FK_F11FB12E61220EA6');
        $this->addSql('ALTER TABLE bookable_metadata DROP FOREIGN KEY FK_F11FB12E7E3C61F9');
        $this->addSql('ALTER TABLE bookable_metadata DROP FOREIGN KEY FK_F11FB12EE37ECFB0');
        $this->addSql('ALTER TABLE bookable_metadata ADD CONSTRAINT FK_F11FB12E61220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookable_metadata ADD CONSTRAINT FK_F11FB12E7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookable_metadata ADD CONSTRAINT FK_F11FB12EE37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D161220EA6');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D17E3C61F9');
        $this->addSql('ALTER TABLE transaction DROP FOREIGN KEY FK_723705D1E37ECFB0');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D161220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D17E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE accounting_document DROP FOREIGN KEY FK_60EDA78461220EA6');
        $this->addSql('ALTER TABLE accounting_document DROP FOREIGN KEY FK_60EDA7847E3C61F9');
        $this->addSql('ALTER TABLE accounting_document DROP FOREIGN KEY FK_60EDA784E37ECFB0');
        $this->addSql('ALTER TABLE accounting_document ADD CONSTRAINT FK_60EDA78461220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE accounting_document ADD CONSTRAINT FK_60EDA7847E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE accounting_document ADD CONSTRAINT FK_60EDA784E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction_line DROP FOREIGN KEY FK_33578A5761220EA6');
        $this->addSql('ALTER TABLE transaction_line DROP FOREIGN KEY FK_33578A577E3C61F9');
        $this->addSql('ALTER TABLE transaction_line DROP FOREIGN KEY FK_33578A57E37ECFB0');
        $this->addSql('ALTER TABLE transaction_line ADD CONSTRAINT FK_33578A5761220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction_line ADD CONSTRAINT FK_33578A577E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction_line ADD CONSTRAINT FK_33578A57E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE expense_claim DROP FOREIGN KEY FK_461791D61220EA6');
        $this->addSql('ALTER TABLE expense_claim DROP FOREIGN KEY FK_461791D7E3C61F9');
        $this->addSql('ALTER TABLE expense_claim DROP FOREIGN KEY FK_461791DE37ECFB0');
        $this->addSql('ALTER TABLE expense_claim ADD CONSTRAINT FK_461791D61220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE expense_claim ADD CONSTRAINT FK_461791D7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE expense_claim ADD CONSTRAINT FK_461791DE37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookable_tag DROP FOREIGN KEY FK_C360AD1261220EA6');
        $this->addSql('ALTER TABLE bookable_tag DROP FOREIGN KEY FK_C360AD127E3C61F9');
        $this->addSql('ALTER TABLE bookable_tag DROP FOREIGN KEY FK_C360AD12E37ECFB0');
        $this->addSql('ALTER TABLE bookable_tag ADD CONSTRAINT FK_C360AD1261220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookable_tag ADD CONSTRAINT FK_C360AD127E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookable_tag ADD CONSTRAINT FK_C360AD12E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE license DROP FOREIGN KEY FK_5768F41961220EA6');
        $this->addSql('ALTER TABLE license DROP FOREIGN KEY FK_5768F4197E3C61F9');
        $this->addSql('ALTER TABLE license DROP FOREIGN KEY FK_5768F419E37ECFB0');
        $this->addSql('ALTER TABLE license ADD CONSTRAINT FK_5768F41961220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE license ADD CONSTRAINT FK_5768F4197E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE license ADD CONSTRAINT FK_5768F419E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
    }
}
