<?php

declare(strict_types=1);

namespace Application\Migration;

use Doctrine\DBAL\Schema\Schema;

class Version20190422061349 extends AbstractMigration
{
    public function up(Schema $schema): void
    {
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'mysql', 'Migration can only be executed safely on \'mysql\'.');

        $this->addSql('CREATE TABLE log (id INT AUTO_INCREMENT NOT NULL, creator_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, updater_id INT DEFAULT NULL, creation_date DATETIME DEFAULT NULL, update_date DATETIME DEFAULT NULL, priority SMALLINT NOT NULL, message VARCHAR(5000) NOT NULL, referer VARCHAR(500) NOT NULL, request VARCHAR(1000) NOT NULL, ip VARCHAR(40) NOT NULL, extra LONGTEXT NOT NULL COMMENT \'(DC2Type:json_array)\', url VARCHAR(2000) NOT NULL, INDEX IDX_8F3F68C561220EA6 (creator_id), INDEX IDX_8F3F68C57E3C61F9 (owner_id), INDEX IDX_8F3F68C5E37ECFB0 (updater_id), INDEX priority (creation_date), INDEX date_created (creation_date), INDEX message (message), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user (id INT AUTO_INCREMENT NOT NULL, creator_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, updater_id INT DEFAULT NULL, creation_date DATETIME DEFAULT NULL, update_date DATETIME DEFAULT NULL, login VARCHAR(50) DEFAULT NULL, first_name VARCHAR(191) NOT NULL, last_name VARCHAR(191) NOT NULL, password VARCHAR(255) NOT NULL, email VARCHAR(191) DEFAULT NULL, role ENUM(\'partner\', \'individual\', \'member\', \'responsible\', \'administrator\') DEFAULT \'individual\' NOT NULL COMMENT \'(DC2Type:UserRole)\', status ENUM(\'inactive\', \'active\', \'new\', \'archived\') DEFAULT \'new\' NOT NULL COMMENT \'(DC2Type:UserStatus)\', welcome_session_date DATETIME DEFAULT NULL, resign_date DATETIME DEFAULT NULL, sex SMALLINT DEFAULT 0 NOT NULL, phone VARCHAR(25) DEFAULT \'\' NOT NULL, mobile_phone VARCHAR(25) DEFAULT \'\' NOT NULL, swiss_sailing VARCHAR(25) DEFAULT \'\' NOT NULL, swiss_sailing_type ENUM(\'active\', \'passive\', \'junior\') DEFAULT NULL COMMENT \'(DC2Type:SwissSailingType)\', swiss_windsurf_type ENUM(\'active\', \'passive\') DEFAULT NULL COMMENT \'(DC2Type:SwissWindsurfType)\', birthday DATE DEFAULT NULL, terms_agreement TINYINT(1) DEFAULT \'0\' NOT NULL, has_insurance TINYINT(1) DEFAULT \'0\' NOT NULL, receives_newsletter TINYINT(1) DEFAULT \'0\' NOT NULL, family_relationship ENUM(\'householder\', \'partner\', \'child\', \'parent\', \'sister\', \'brother\') DEFAULT \'householder\' NOT NULL COMMENT \'(DC2Type:Relationship)\', billing_type ENUM(\'electronic\', \'paper\') DEFAULT \'electronic\' NOT NULL COMMENT \'(DC2Type:BillingType)\', token VARCHAR(32) DEFAULT NULL, token_creation_date DATETIME DEFAULT NULL, door1 TINYINT(1) DEFAULT \'1\' NOT NULL, door2 TINYINT(1) DEFAULT \'1\' NOT NULL, door3 TINYINT(1) DEFAULT \'1\' NOT NULL, door4 TINYINT(1) DEFAULT \'0\' NOT NULL, remarks TEXT NOT NULL, internal_remarks TEXT NOT NULL, street VARCHAR(255) NOT NULL, postcode VARCHAR(20) NOT NULL, locality VARCHAR(255) NOT NULL, iban VARCHAR(34) DEFAULT \'\' NOT NULL, UNIQUE INDEX UNIQ_8D93D649AA08CB10 (login), UNIQUE INDEX UNIQ_8D93D649E7927C74 (email), UNIQUE INDEX UNIQ_8D93D6495F37A13B (token), INDEX IDX_8D93D64961220EA6 (creator_id), INDEX IDX_8D93D6497E3C61F9 (owner_id), INDEX IDX_8D93D649E37ECFB0 (updater_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_tag (id INT AUTO_INCREMENT NOT NULL, creator_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, updater_id INT DEFAULT NULL, creation_date DATETIME DEFAULT NULL, update_date DATETIME DEFAULT NULL, name VARCHAR(191) NOT NULL, color VARCHAR(7) DEFAULT \'\' NOT NULL, INDEX IDX_E89FD60861220EA6 (creator_id), INDEX IDX_E89FD6087E3C61F9 (owner_id), INDEX IDX_E89FD608E37ECFB0 (updater_id), UNIQUE INDEX unique_name (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE user_tag_user (user_tag_id INT NOT NULL, user_id INT NOT NULL, INDEX IDX_83118DFFDF80782C (user_tag_id), INDEX IDX_83118DFFA76ED395 (user_id), PRIMARY KEY(user_tag_id, user_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE message (id INT AUTO_INCREMENT NOT NULL, creator_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, updater_id INT DEFAULT NULL, recipient_id INT DEFAULT NULL, creation_date DATETIME DEFAULT NULL, update_date DATETIME DEFAULT NULL, email VARCHAR(191) NOT NULL, type ENUM(\'register\', \'unregister\', \'reset_password\', \'balance\') NOT NULL COMMENT \'(DC2Type:MessageType)\', date_sent DATETIME DEFAULT NULL, subject VARCHAR(255) DEFAULT \'\' NOT NULL, body TEXT NOT NULL, INDEX IDX_B6BD307F61220EA6 (creator_id), INDEX IDX_B6BD307F7E3C61F9 (owner_id), INDEX IDX_B6BD307FE37ECFB0 (updater_id), INDEX IDX_B6BD307FE92F8F78 (recipient_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bookable (id INT AUTO_INCREMENT NOT NULL, creator_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, updater_id INT DEFAULT NULL, image_id INT DEFAULT NULL, credit_account_id INT DEFAULT NULL, creation_date DATETIME DEFAULT NULL, update_date DATETIME DEFAULT NULL, initial_price NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, periodic_price NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, purchase_price NUMERIC(10, 2) UNSIGNED DEFAULT \'0.00\' NOT NULL, is_active TINYINT(1) DEFAULT \'1\' NOT NULL, state ENUM(\'good\', \'used\', \'degraded\') DEFAULT \'good\' NOT NULL COMMENT \'(DC2Type:BookableState)\', verification_date DATE DEFAULT NULL, name VARCHAR(191) NOT NULL, description TEXT NOT NULL, code VARCHAR(10) DEFAULT \'\' NOT NULL, remarks TEXT NOT NULL, INDEX IDX_A10B812461220EA6 (creator_id), INDEX IDX_A10B81247E3C61F9 (owner_id), INDEX IDX_A10B8124E37ECFB0 (updater_id), UNIQUE INDEX UNIQ_A10B81243DA5256D (image_id), INDEX IDX_A10B81246813E404 (credit_account_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE image (id INT AUTO_INCREMENT NOT NULL, creator_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, updater_id INT DEFAULT NULL, creation_date DATETIME DEFAULT NULL, update_date DATETIME DEFAULT NULL, filename VARCHAR(190) NOT NULL, mime VARCHAR(255) NOT NULL, width INT NOT NULL, height INT NOT NULL, INDEX IDX_C53D045F61220EA6 (creator_id), INDEX IDX_C53D045F7E3C61F9 (owner_id), INDEX IDX_C53D045FE37ECFB0 (updater_id), UNIQUE INDEX unique_name (filename), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE account (id INT AUTO_INCREMENT NOT NULL, creator_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, updater_id INT DEFAULT NULL, parent_id INT DEFAULT NULL, creation_date DATETIME DEFAULT NULL, update_date DATETIME DEFAULT NULL, balance NUMERIC(10, 2) DEFAULT \'0.00\' NOT NULL, type ENUM(\'asset\', \'liability\', \'revenue\', \'expense\', \'equity\', \'group\') NOT NULL COMMENT \'(DC2Type:AccountType)\', code VARCHAR(10) NOT NULL, name VARCHAR(191) NOT NULL, iban VARCHAR(34) DEFAULT \'\' NOT NULL, UNIQUE INDEX UNIQ_7D3656A477153098 (code), INDEX IDX_7D3656A461220EA6 (creator_id), UNIQUE INDEX UNIQ_7D3656A47E3C61F9 (owner_id), INDEX IDX_7D3656A4E37ECFB0 (updater_id), INDEX IDX_7D3656A4727ACA70 (parent_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transaction_tag (id INT AUTO_INCREMENT NOT NULL, creator_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, updater_id INT DEFAULT NULL, creation_date DATETIME DEFAULT NULL, update_date DATETIME DEFAULT NULL, name VARCHAR(191) NOT NULL, color VARCHAR(7) DEFAULT \'\' NOT NULL, INDEX IDX_F8CD024A61220EA6 (creator_id), INDEX IDX_F8CD024A7E3C61F9 (owner_id), INDEX IDX_F8CD024AE37ECFB0 (updater_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bookable_metadata (id INT AUTO_INCREMENT NOT NULL, creator_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, updater_id INT DEFAULT NULL, bookable_id INT DEFAULT NULL, creation_date DATETIME DEFAULT NULL, update_date DATETIME DEFAULT NULL, value VARCHAR(191) DEFAULT \'\' NOT NULL, name VARCHAR(191) NOT NULL, INDEX IDX_F11FB12E61220EA6 (creator_id), INDEX IDX_F11FB12E7E3C61F9 (owner_id), INDEX IDX_F11FB12EE37ECFB0 (updater_id), INDEX IDX_F11FB12EEC4F5B2F (bookable_id), UNIQUE INDEX unique_name (name, bookable_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transaction (id INT AUTO_INCREMENT NOT NULL, creator_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, updater_id INT DEFAULT NULL, expense_claim_id INT DEFAULT NULL, creation_date DATETIME DEFAULT NULL, update_date DATETIME DEFAULT NULL, transactionDate DATE NOT NULL, datatrans_ref VARCHAR(18) DEFAULT \'\' NOT NULL, name VARCHAR(191) NOT NULL, remarks TEXT NOT NULL, internal_remarks TEXT NOT NULL, INDEX IDX_723705D161220EA6 (creator_id), INDEX IDX_723705D17E3C61F9 (owner_id), INDEX IDX_723705D1E37ECFB0 (updater_id), INDEX IDX_723705D1B6F76666 (expense_claim_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE accounting_document (id INT AUTO_INCREMENT NOT NULL, creator_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, updater_id INT DEFAULT NULL, expense_claim_id INT DEFAULT NULL, transaction_id INT DEFAULT NULL, creation_date DATETIME DEFAULT NULL, update_date DATETIME DEFAULT NULL, filename VARCHAR(190) NOT NULL, mime VARCHAR(255) NOT NULL, INDEX IDX_60EDA78461220EA6 (creator_id), INDEX IDX_60EDA7847E3C61F9 (owner_id), INDEX IDX_60EDA784E37ECFB0 (updater_id), INDEX IDX_60EDA784B6F76666 (expense_claim_id), INDEX IDX_60EDA7842FC0CB0F (transaction_id), UNIQUE INDEX unique_name (filename), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE transaction_line (id INT AUTO_INCREMENT NOT NULL, creator_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, updater_id INT DEFAULT NULL, transaction_id INT NOT NULL, debit_id INT DEFAULT NULL, credit_id INT DEFAULT NULL, bookable_id INT DEFAULT NULL, transaction_tag_id INT DEFAULT NULL, creation_date DATETIME DEFAULT NULL, update_date DATETIME DEFAULT NULL, balance NUMERIC(10, 2) UNSIGNED NOT NULL, transactionDate DATE NOT NULL, is_reconciled TINYINT(1) DEFAULT \'0\' NOT NULL, name VARCHAR(191) NOT NULL, remarks TEXT NOT NULL, INDEX IDX_33578A5761220EA6 (creator_id), INDEX IDX_33578A577E3C61F9 (owner_id), INDEX IDX_33578A57E37ECFB0 (updater_id), INDEX IDX_33578A572FC0CB0F (transaction_id), INDEX IDX_33578A57444E82EE (debit_id), INDEX IDX_33578A57CE062FF9 (credit_id), INDEX IDX_33578A57EC4F5B2F (bookable_id), INDEX IDX_33578A57CCAF1151 (transaction_tag_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE expense_claim (id INT AUTO_INCREMENT NOT NULL, creator_id INT DEFAULT NULL, owner_id INT NOT NULL, updater_id INT DEFAULT NULL, creation_date DATETIME DEFAULT NULL, update_date DATETIME DEFAULT NULL, amount NUMERIC(10, 2) UNSIGNED NOT NULL, status ENUM(\'new\', \'processing\', \'processed\', \'rejected\') DEFAULT \'new\' NOT NULL COMMENT \'(DC2Type:ExpenseClaimStatus)\', type ENUM(\'expenseClaim\', \'refund\') DEFAULT \'expenseClaim\' NOT NULL COMMENT \'(DC2Type:ExpenseClaimType)\', name VARCHAR(191) NOT NULL, description TEXT NOT NULL, remarks TEXT NOT NULL, internal_remarks TEXT NOT NULL, INDEX IDX_461791D61220EA6 (creator_id), INDEX IDX_461791D7E3C61F9 (owner_id), INDEX IDX_461791DE37ECFB0 (updater_id), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bookable_tag (id INT AUTO_INCREMENT NOT NULL, creator_id INT DEFAULT NULL, owner_id INT DEFAULT NULL, updater_id INT DEFAULT NULL, creation_date DATETIME DEFAULT NULL, update_date DATETIME DEFAULT NULL, name VARCHAR(191) NOT NULL, color VARCHAR(7) DEFAULT \'\' NOT NULL, INDEX IDX_C360AD1261220EA6 (creator_id), INDEX IDX_C360AD127E3C61F9 (owner_id), INDEX IDX_C360AD12E37ECFB0 (updater_id), UNIQUE INDEX unique_name (name), PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('CREATE TABLE bookable_tag_bookable (bookable_tag_id INT NOT NULL, bookable_id INT NOT NULL, INDEX IDX_207F7C112FF81111 (bookable_tag_id), INDEX IDX_207F7C11EC4F5B2F (bookable_id), PRIMARY KEY(bookable_tag_id, bookable_id)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci ENGINE = InnoDB');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C561220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C57E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE log ADD CONSTRAINT FK_8F3F68C5E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D64961220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D6497E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user ADD CONSTRAINT FK_8D93D649E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_tag ADD CONSTRAINT FK_E89FD60861220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_tag ADD CONSTRAINT FK_E89FD6087E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_tag ADD CONSTRAINT FK_E89FD608E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE user_tag_user ADD CONSTRAINT FK_83118DFFDF80782C FOREIGN KEY (user_tag_id) REFERENCES user_tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE user_tag_user ADD CONSTRAINT FK_83118DFFA76ED395 FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F61220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FE37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE message ADD CONSTRAINT FK_B6BD307FE92F8F78 FOREIGN KEY (recipient_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bookable ADD CONSTRAINT FK_A10B812461220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookable ADD CONSTRAINT FK_A10B81247E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookable ADD CONSTRAINT FK_A10B8124E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookable ADD CONSTRAINT FK_A10B81243DA5256D FOREIGN KEY (image_id) REFERENCES image (id)');
        $this->addSql('ALTER TABLE bookable ADD CONSTRAINT FK_A10B81246813E404 FOREIGN KEY (credit_account_id) REFERENCES account (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045F61220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045F7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE image ADD CONSTRAINT FK_C53D045FE37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A461220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A47E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A4E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE account ADD CONSTRAINT FK_7D3656A4727ACA70 FOREIGN KEY (parent_id) REFERENCES account (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE transaction_tag ADD CONSTRAINT FK_F8CD024A61220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction_tag ADD CONSTRAINT FK_F8CD024A7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction_tag ADD CONSTRAINT FK_F8CD024AE37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookable_metadata ADD CONSTRAINT FK_F11FB12E61220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookable_metadata ADD CONSTRAINT FK_F11FB12E7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookable_metadata ADD CONSTRAINT FK_F11FB12EE37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookable_metadata ADD CONSTRAINT FK_F11FB12EEC4F5B2F FOREIGN KEY (bookable_id) REFERENCES bookable (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D161220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D17E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction ADD CONSTRAINT FK_723705D1B6F76666 FOREIGN KEY (expense_claim_id) REFERENCES expense_claim (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE accounting_document ADD CONSTRAINT FK_60EDA78461220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE accounting_document ADD CONSTRAINT FK_60EDA7847E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE accounting_document ADD CONSTRAINT FK_60EDA784E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE accounting_document ADD CONSTRAINT FK_60EDA784B6F76666 FOREIGN KEY (expense_claim_id) REFERENCES expense_claim (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE accounting_document ADD CONSTRAINT FK_60EDA7842FC0CB0F FOREIGN KEY (transaction_id) REFERENCES transaction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE transaction_line ADD CONSTRAINT FK_33578A5761220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction_line ADD CONSTRAINT FK_33578A577E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction_line ADD CONSTRAINT FK_33578A57E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction_line ADD CONSTRAINT FK_33578A572FC0CB0F FOREIGN KEY (transaction_id) REFERENCES transaction (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE transaction_line ADD CONSTRAINT FK_33578A57444E82EE FOREIGN KEY (debit_id) REFERENCES account (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE transaction_line ADD CONSTRAINT FK_33578A57CE062FF9 FOREIGN KEY (credit_id) REFERENCES account (id) ON DELETE RESTRICT');
        $this->addSql('ALTER TABLE transaction_line ADD CONSTRAINT FK_33578A57EC4F5B2F FOREIGN KEY (bookable_id) REFERENCES bookable (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE transaction_line ADD CONSTRAINT FK_33578A57CCAF1151 FOREIGN KEY (transaction_tag_id) REFERENCES transaction_tag (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE expense_claim ADD CONSTRAINT FK_461791D61220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE expense_claim ADD CONSTRAINT FK_461791D7E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE expense_claim ADD CONSTRAINT FK_461791DE37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookable_tag ADD CONSTRAINT FK_C360AD1261220EA6 FOREIGN KEY (creator_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookable_tag ADD CONSTRAINT FK_C360AD127E3C61F9 FOREIGN KEY (owner_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookable_tag ADD CONSTRAINT FK_C360AD12E37ECFB0 FOREIGN KEY (updater_id) REFERENCES user (id) ON DELETE SET NULL');
        $this->addSql('ALTER TABLE bookable_tag_bookable ADD CONSTRAINT FK_207F7C112FF81111 FOREIGN KEY (bookable_tag_id) REFERENCES bookable_tag (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE bookable_tag_bookable ADD CONSTRAINT FK_207F7C11EC4F5B2F FOREIGN KEY (bookable_id) REFERENCES bookable (id) ON DELETE CASCADE');
    }
}
