<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
        <link rel="icon" type="image/x-icon" href="favicon.ico">
        <?php echo $this->headTitle('Ichtus')->setSeparator(' - ')->setAutoEscape(false) ?>
    </head>
    <body>
        <?php echo $this->content ?>
    </body>
</html>
