<?php declare(strict_types=1);
$url = $this->serverUrl . '/change-password/' . $this->token;
?>
<p>Une demande de modification de mot de passe a été faite pour le login "<?php echo $this->user->getLogin() ?>". Pour choisir un nouveau mot de passe, suivez le lien suivant :</p>

<p><a href="<?php echo $url ?>"><?php echo $url ?></a></p>

<p>
    Si vous n'êtes pas à l'origine de cette demande, et que cela ne concerne pas un membre de votre famille, vous pouvez simplement ignorer cet email.
</p>

